# Generated by Django 5.1.2 on 2024-10-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='cover_picture',
            field=models.ImageField(null=True, upload_to='cover_picture/'),
        ),
    ]
