# Generated by Django 5.1.2 on 2024-10-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_home', '0002_personaldetails_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
